language: python

os:
  - linux
  # travis does not support Python on OS X builds.
  # - osx

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34

# Command to install
install:
  - pip install -r requirements.txt
  - python setup.py install

# Command to run tests.
script:
  - tox -e $TOXENV

after_success:
  - pip install pytest coverage codeclimate-test-reporter
  - coverage run --source meshing -m pytest
  - codeclimate-test-reporter --file .coverage

addons:
  code_climate:
    repo_token: 3a10621b32482135d291ea233566de6dad2320a696406e598226b835f09c7dc3